// <auto-generated />
namespace ITClassWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add16 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add16));
        
        string IMigrationMetadata.Id
        {
            get { return "201906210846508_add16"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
