// <auto-generated />
namespace ITClassWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add18 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add18));
        
        string IMigrationMetadata.Id
        {
            get { return "201906211021125_add18"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
